# PRODUCT CATEGORIES
MAX_CATEGORY_NAME_LENGTH = 142
MAX_CATEGORIES_COUNT = 20

# If product description length bigger than this integer
# description will be sends as separate message
MAX_TEMP_DESCRIPTION_LENGTH = 150

# PRODUCT VALIDATION
MAX_PRODUCT_NAME_LENGTH = 50

# BUTTONS VALIDATION
MAX_BUTTON_NAME_LENGTH = 142
MAX_BUTTON_CONTENT_COUNT = 10

# ADDRESSES VALIDATION
MIN_ADDRESS_LENGTH = 5
MAX_ADDRESS_LENGTH = 300
